### PR TITLE
Show worded lined

### LINKED ISSUE #143: Add _Show
https://hackage.haskell.org/package/lens/docs/Control-Lens-Combinators.html#v:_Show

Obviously the type would have to be changed to

```haskell
(Read a, Show a) => Traversal' String a
```

Additionally, the name seems backwards if it's going to be a Traversal:  the value is being viewed as _read_ rather than as _shown_.  But oh well, it's a Prism, it looks like a constructor if you squint, and it's been in `lens` for years.

I personally use this one quite a bit.  Happy to toss it in if you approve of the idea.

### LINKED ISSUE #144: Add worded and lined
```haskell
worded, lined :: Traversal' String String
```

Same ballpark as #143.  These are improper as documented [here](https://hackage.haskell.org/package/lens-4.19.2/docs/Control-Lens-Combinators.html#v:worded).

### PR DESCRIPTION
**Pull request by sjshuck**
Fixes #143.  Fixes #144.

### CODE REVIEW

**Comment by neongreen** [comment]
My work laptop is being repaired atm, so I'll merge this and make a new release when I get it back.

**Comment by sjshuck** [comment]
No rush, good luck with that.

**Comment by stevenfontanella** [comment]
Thank you @sjshuck. Will create a new release soon.

**Comment by stevenfontanella** [comment]
Released https://hackage.haskell.org/package/microlens-0.4.13.0

**Comment by sjshuck** [comment]
No rush, good luck with that

**Pull request merged**
