### PR TITLE
added microlens-generic

### PR DESCRIPTION
**Pull request by BebeSparkelSparkel**
An incomplete implementation but a start.

### CODE REVIEW

**Comment by stevenfontanella** [comment]
Hi William, what do you plan to use this library for? Does `lens` have an equivalent? I see some similar definitions [here](https://hackage.haskell.org/package/lens-5.2.3/docs/GHC-Generics-Lens.html) but not quite the same, is this what you're aiming to port over?

**Comment by BebeSparkelSparkel** [comment]
Thanks for asking. I am not trying to define optics for the generic types but rather allow for ADT with the Generic instance to be operated on with product lenses _1, _2, ... and and sum lenses _Left, _Right (for sums it might be better to have _s1, _s2, ...) so that I can quickly test things out and do not have to use TH.

**Comment by stevenfontanella** [comment]
Got it, thanks for the quick answer and apologies for the delay.

I'm curious: why not use microlens-th for prototyping and later remove the dependency and write your own lenses from scratch later if needed? If this library is only meant for prototyping purposes, then it seems that anyway you would have to remove the Generic derivations + replace the usages e.g. (_1), later on, which seems no less difficult than if you had used microlens-th.

In any case, I don't think this library needs to live in this repo. It looks like a normal library that depends on microlens rather than a 'core' microlens library. If you'd like, please feel free to start another repro and upload it to hackage yourself.

**Comment by BebeSparkelSparkel** [comment]
Thanks for your feed back. I'll look into your suggestion of TH.

**Pull request closed without merging**
