### PR TITLE
Port StarIsType fix to GHC 7

### PR DESCRIPTION
**Pull request by andreasabel**
Continues this PR (I cannot push to it):
- #159

### CODE REVIEW

**Comment by andreasabel** [comment]
Dunno why CI does not run here.  I tested this locally with GHC 7.10 and 9.4.

**Comment by stevenfontanella** [comment]
Thanks Andreas! I see that it works on GHC 9.4. I can't seem to install GHC 7 on my machine (I get a seg fault), but your fix looks correct. Let me try the CI too.

**Comment by andreasabel** [comment]
That CI does not run here seems to be a bug in GitHub.  Since I continued your branch in my branch, when I opened the PR it was not opened against `master` but your branch.  CI is set up to run only on PRs against `master`, to prevent duplicate CI runs.  I then changed the PR base to `master`, but this did not trigger a CI run.

> Let me try the CI too.

- #163

**Comment by stevenfontanella** [comment]
Will create a patch release with this and #161

**Pull request merged**
