### PR TITLE
Permit text-2.0

### PR DESCRIPTION
**Pull request by sjshuck**
Fixes stevenfontanella/microlens#154.

### CODE REVIEW

**Review by fosskers — APPROVED** [review]
I also have merge rights, but I'll wait for @stevenfontanella .

**Comment by stevenfontanella** [comment]
Thanks for opening this. Can you just upgrade the patch version of microlens-platform (to 0.4.3.1)? I was going to add it myself but I don't have permission to your branch.

**Comment by fosskers** [comment]
@stevenfontanella I think Github made an update such that owners of the original (non-fork) repo can push to branches of forks, letting you amend PRs directly.

**Comment by stevenfontanella** [comment]
@fosskers not sure, I did

```
git remote add sjshuck git@github.com:sjshuck/microlens.git
git push -u sjshuck master
```

but I got a permission denied error. I remember when opening a PR there is a checkbox somewhere that the author can allow contributions, I was thinking that was probably not checked.

**Comment by stevenfontanella** [comment]
Released https://hackage.haskell.org/package/microlens-platform-0.4.3.1

**Comment by sjshuck** [comment]
Thanks 🎉

**Pull request merged**
